"use client";

import { AnymotionPlayer } from "..";

interface SpinnerDeCargaAnimadoPlayerProps {
  controls?: boolean;
  autoPlay?: boolean;
  caption?: string;
}

/**
 * React integration for the "Spinner de carga animado" animation.
 *
 * Generated by `npm run anim:convert -- --slug spinner-demo`. Renders the
 * Anymotion HTML output in a sandboxed iframe with optional external
 * playback controls. Edit freely — this file is a scaffold, not a lock.
 */
export function SpinnerDeCargaAnimadoPlayer({ controls = true, autoPlay = false, caption }: SpinnerDeCargaAnimadoPlayerProps) {
  return (
    <AnymotionPlayer
      src="/animations/spinner-demo/index.html"
      title="Spinner de carga animado"
      caption={caption ?? `${controls ? "Avanza la línea de tiempo para ver cada frame de la animación." : ""}`}
      controls={controls}
      autoPlay={autoPlay}
    />
  );
}
